version: '3'
services:
  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: Dockerfile

    ports:
      - 8081:8080
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
  backend:
    image: backend
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongo/coyoject3
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./backend/src:/app/src
      - ./backend/tests:/app/tests
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data
